### ISSUE TITLE
The SASS plugin only support the SCSS syntax

### ISSUE THREAD

**Issue by Hunam6** [alephjs/aleph.js#40]
When using the SASS syntax it throws a syntax error.

**Comment by Hunam6** [comment]
Working:
```scss
body {
  background: lightblue;
}
```
Not working:
```sass
body
  background: lightblue
```
