### ISSUE TITLE
Css fonts are not imported

### ISSUE THREAD

**Issue by tomkimsour** [alephjs/aleph.js#459]
Am I the only person who has a problem with fonts ?
I just did this but none of the fonts are used
```css
@font-face {
  font-family: NeueMontreal;
  src: url("/fonts/PPNeueMontreal-Book.otf") format("opentype");
}

body {
  padding-left: 140px;
  padding-right: 140px;
  letter-spacing: 0pt;
  font-size: 16px;
  font-family:
    NeueMontreal,
    Inter,
    system-ui,
    -apple-system, Firefox supports this but not yet `system-ui`
    'Segoe UI', 
    Roboto,
    Helvetica,
    Arial,
    sans-serif,
    'Apple Color Emoji',
    'Segoe UI Emoji';
}
```
